teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.15
        
    axis_linear: # right thumb stick horizontal
      y: 2
    scale_linear:
      y: 0.3
    scale_linear_turbo:
      y: 0.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.4
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 6  # Left trigger button
    enable_turbo_button: 7  # Right trigger button
